### ISSUE TITLE
Build Errors after importing plugin

### ISSUE THREAD

**Issue by CatalinMustata** [StephenGuanqi/Unity-ARKit-Plugin#4]
Hi there,

I'm getting the following errors after installing the plugin:

```Assets/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs(146,10): error CS0246: The type or namespace name `UnityVideoParams' could not be found. Are you missing an assembly reference?```
```Assets/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs(147,10): error CS0246: The type or namespace name `UnityARLightEstimate' could not be found. Are you missing an assembly reference?```
```Assets/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs(288,70): error CS0246: The type or namespace name `ARKitWorldTrackingSessionConfiguration' could not be found. Are you missing an assembly reference?```

Any idea what's wrong?

I'm using Unity 2017.1.1p4 and the latest Unity-ARKit-Plugin (official)

**Comment by StephenGuanqi** [comment]
The truth is that I haven't committed the some core files due to some submodule problem in git. I made some sub repositories in main repo and fail to commit all of them. 

I have just fixed that problem and please fetch the newest commit.

I'm really sorry about the problem.

**Comment by royepeer** [comment]
Still having the same issue, here are 2 of the 61 I received after import:

Assets/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs(258,61): error CS0246: The type or namespace name `UnityARCamera' could not be found. Are you missing an assembly reference?

Assets/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs(518,35): error CS0246: The type or namespace name `ARKitWorldTrackingSessionConfiguration' could not be found. Are you missing an assembly reference?
